---
- name: Implementing play scope variable
  hosts: all
  vars:
    - a: tomcat9
    - b: present
    - c: yes
  tasks:
    - name: Install/uninstall s/w using play scope
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...  
