---
- name: install git on all servers
  hosts: all
  tasks:
    - name: install git o ubuntu  server
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
    - name: install giton centos server
      yum:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "CentOS"
...

