---
- name: Implementing hoste scope variable
  hosts: 172.31.45.183
  tasks:
    - name: create users
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
        home: "{{d}}"
        comment: "{{e}}"
        shell: "{{f}}"
...
