---
- name: implementing tags
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: install tree
      apt:
        name: tree
        state: present
        update_cache: yes
      tags: tree_installation
    - name: create user
      user:
        name: Anusha
        password: 123456
      tags: user_creation
    - name: copy password file
      copy:
        src: /etc/passwd
        dest: /tmp
...
